# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  #   branches:
  #     - main
  #     - 'releases/**'
  # workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: | 
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: running from my brnach
        run: |
          echo "New changes"
