name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: 
  contents: read
  packages: write
jobs:
  login:
    runs-on: ubuntu-latest
    steps:

      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'sadmin123'
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -       
       name: Build and push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: sadmin123/localdemo:${{ github.sha }}