name: Share data between jobs
on:
    workflow_dispatch: {}
jobs:
    check-out-stage:
        name: check-out-stage
        runs-on: ubuntu-22.04
        steps:
            - name: clone git repo
              uses: actions/checkout@v4

            - name: List code repo files
              run: |
                ls -ltr
            
            # - name: create folder
            #   run: |
            #     mkdir -p temp/code
            #     cp -rvf * temp/code/
            
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: app-artifacts
                path: '*'
            
            
    Job2:
      name: Access check-out-stage  files
      runs-on: ubuntu-22.04
      needs: [check-out-stage]
      steps:
        - name: Download app artifacts
          uses: actions/download-artifact@v4
          with:
            name: app-artifacts
            
        - name: List files from Job2
          run: |
            ls -ltra


#   Upload-Artifacts:
#     name: Upload File
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello World" > file.txt
#       - uses: actions/upload-artifact@v4
#         with:
#           name: file
#           path: file.txt

#   Download-Artifacts:
#     name: Download File
#     runs-on: ubuntu-latest
#     needs: Upload-Artifacts
#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           name: file
#       - name: Print Download file
#         run: cat file.txt

#   Upload-Multiple-Artifacts:
#     name: multiple artifacts upload
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v4
#         with:
#             fetch-depth: 0
      
#       - name: run list files condition
#         run: ls -ltr
#       - name: create directory and move files
#         run: |-
#              mkdir  -p workspace/repo
#              mv * workspace/repo/
      
#       - name: Upload artifacts
#         uses: actions/upload-artifact@v4
#         with:
#             name: multiple-files
#             path: workspace/repo/

#   Download-Multi-ple-Artifacts:
#     name: Download File
#     runs-on: ubuntu-latest
#     needs: [Upload-Multiple-Artifacts]
#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           name: multiple-files
#       - name: Print Download file
#         run: |
#             ls -ltr 